Resources:
  PersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Persons-${self:provider.stage}
      KeySchema:
        - AttributeName: personId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: personId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
# Export table name
Outputs:
  PersonsTableName:
    Description: Name of the DynamoDB table
    Value:
      Ref: PersonsTable
    Export:
      Name: "PersonsTableName-${self:custom.name}"
