service: ${self:custom.serviceName}

frameworkVersion: ">3.0.0"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: "${file(../serverless.yml):provider.region}"
  versionFunctions: false
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    name: ${self:custom.serviceName}-${self:provider.stage}-deploys
    serverSideEncryption: AES256

resources: ${file(resources/resources.yml)}

plugins:
  - serverless-deployment-bucket

custom:
  name: "${self:service}-${self:provider.stage}"
  region: "${file(../serverless.yml):custom.region}"
  accountId: ${aws:accountId}
  serviceName: database
